{"created": 1614939540.8742409, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null}
{"created": 1614939553.5411355, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null}
{"created": 1614939738.9676938, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null, "exc_info": "Traceback (most recent call last):\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_protocol.py\", line 422, in _handle_request\n    resp = await self._request_handler(request)\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_app.py\", line 499, in _handle\n    resp = await handler(request)\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\api\\main.py\", line 17, in create_task\n    data = await request.json()\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_request.py\", line 614, in json\n    return loads(body)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}
{"created": 1614939925.403193, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null, "exc_info": "Traceback (most recent call last):\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_protocol.py\", line 422, in _handle_request\n    resp = await self._request_handler(request)\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_app.py\", line 499, in _handle\n    resp = await handler(request)\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\api\\main.py\", line 17, in create_task\n    data = await request.json()\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_request.py\", line 614, in json\n    return loads(body)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}
{"created": 1614939944.676971, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null, "exc_info": "Traceback (most recent call last):\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_protocol.py\", line 422, in _handle_request\n    resp = await self._request_handler(request)\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_app.py\", line 499, in _handle\n    resp = await handler(request)\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\api\\main.py\", line 17, in create_task\n    data = await request.json()\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_request.py\", line 614, in json\n    return loads(body)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}
{"created": 1614940161.9011548, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null, "exc_info": "Traceback (most recent call last):\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_protocol.py\", line 422, in _handle_request\n    resp = await self._request_handler(request)\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_app.py\", line 499, in _handle\n    resp = await handler(request)\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\api\\main.py\", line 18, in create_task\n    data = await request.json()\n  File \"D:\\work\\OpReturn\\Investigation\\panini-pypi\\venv\\lib\\site-packages\\aiohttp\\web_request.py\", line 614, in json\n    return loads(body)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}
{"created": 1614940487.0236828, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null}
{"created": 1614940525.029425, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null}
{"created": 1614940730.2420578, "name": "aiohttp.server", "levelname": "ERROR", "processName": "MainProcess", "threadName": "MainThread", "message": "Error handling request", "extra": null}
